name: 'Publish to Maven Central'

on:
  push:

concurrency:
  group: 'tawra-ktor-api-publish'
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'gradle'
      - name: Publishing to maven central
        run: gradle publishToCentral
        env:
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
